### ISSUE TITLE
Support for Linux and Mac

### ISSUE THREAD

**Issue by NNBnh** [wareya/autotyler#1]
I cannot run `autotyler` on the Linux terminal :(

I don't know anything about Rust or how to run the `.exe` file from the terminal on Linux.

I try this:

```bash
./autotyler.exe nat_minitiles.png test.png mode=minitiles
```

And this is the result:

```
Failed to execute process './autotyler.exe'. Reason:
exec: Exec format error
```

---

I went through some other Rust software and found [Espanso](https://github.com/federico-terzi/espanso): "Cross-platform Text Expander written in Rust" that launches via CLI. It runs on Windows, Mac and Linux... after downloading `espanso-linux.tar.gz` on [Release page](https://github.com/federico-terzi/espanso/releases) and unzipping, it has `espanso` file (without `.exe`). I run:

```bash
./espanso start
```

And it works.

---

So I guess `autotyler` is not compiled to Linux, I hope to see it in the next release :)

**Comment by wareya** [comment]
Software compiled on one linux distribution can't be assumed to run on any other random linux distribution. It can be done, but the person compiling the software needs to be very careful about how/which system libraries are linked into the resulting application.

As a result, the *norm* for linux software is for the distribution to package software itself, or for the user to compile it from scratch before using it.

Compiling Rust software from scratch is extremely straightforward compared to compiling C or C++ software. You just need an up-to-date rust toolchain from `rustup`, then you run `cargo build --release` in the project's root directory (next to Cargo.toml). A binary compiled for your system should be produced under `target/release/`. It might take a few minutes on a slow machine. `rustup` is probably available in your distribution's package manager somewhere.

**Comment by NNBnh** [comment]
Oh ok, thank you XD
